# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeMobile

  target 'BeMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-config', :path => '../node_modules/react-native-config'

    pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  end

  target 'BeMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BeMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BeMobile-tvOS

  target 'BeMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
